spring.application.name=bff
server.port=8080

azure.functions.usuarios.usuarios.url=https://b-users.azurewebsites.net/api/usuarios
azure.functions.libros.url=https://b-books.azurewebsites.net/api/libros
azure.functions.prestamos.url=https://b-books.azurewebsites.net/api/prestamos
azure.functions.clientes.url=https://b-users.azurewebsites.net/api/clientes